# Generated by Django 5.1 on 2024-10-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_remove_category_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
