# Generated by Django 5.1 on 2024-10-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_alter_product_table_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
