# Generated by Django 5.1 on 2024-08-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
