# Generated by Django 5.0.7 on 2024-08-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField()),
                ('month', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.emp')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
