# Generated by Django 5.0.7 on 2024-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='email',
            field=models.CharField(default='p@gmail.com', max_length=30),
        ),
    ]
