# Generated by Django 5.0.7 on 2024-10-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_remove_product_discreption_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='discreption',
        ),
    ]
