# Generated by Django 5.0.7 on 2024-08-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='emp',
        ),
    ]
